/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      animation: {
        glitch1: "glitch1 3s linear infinite",
        glitch2: "glitch2 2s linear infinite",
        glitch3: "glitch3 1s linear infinite",
        glitch4: "glitch4 2s linear infinite",
        glitch5: "glitch5 1s linear infinite",
        glitch6: "glitch6 2s linear infinite",
      },
      colors: {
        akabeni: "#c12828",
        "army-canvas": "#5f7161",
        aquarium: "#316b70",
        "bleached-silk": "#f3f3f3",
        "bleu-de-france": "#2f80ed",
        "brilliant-liquorice": "#555454",
        "byzantine-night-blue": "#6e77f6",
        "dark-tone-ink": "#121212",
        garnish: "#1a954e",
        "island-green": "#27ae60",
        "khmer-curry": "#eb5757",
        magos: "#6a485a",
        "merlins-cloak": "#85586f",
        "mine-rock": "#8e8383",
        ochre: "#d47622",
        "park-avenue": "#475048",
        "rainbow-bright": "#215dad",
        "cool-balaclavas-are-forever": "#16213E",
        "question-mark-block": "#f2994a",
        "sea-challenge": "#29585c",
        shiffurple: "#920fad",
        "vivid-mulberry": "#bd10e0",
      },
      fontFamily: {
        "plex-mono": ["IBM Plex Mono", "monospace"],
        roboto: ["Roboto", "sans-serif"],
        rubik: ["Rubik", "sans-serif"],
      },
      keyframes: {
        glitch1: {
          "0%": { opacity: 1 },
          "50%": { opacity: 1 },
          "51%": { opacity: 0 },
          "100%": { opacity: 0 },
        },
        glitch2: {
          "0%": { opacity: 0 },
          "50%": { opacity: 0 },
          "51%": { opacity: 0 },
          "53%": { opacity: 0.8 },
          "57%": { opacity: 0.1 },
          "58%": { opacity: 0 },
          "70%": { opacity: 1 },
          "72%": { opacity: 0 },
          "77%": { opacity: 1 },
          "78%": { opacity: 0 },
          "100%": { opacity: 0 },
        },
        glitch3: {
          "0%": { opacity: 0 },
          "50%": { opacity: 0 },
          "51%": { opacity: 0 },
          "59%": { opacity: 0 },
          "61%": { opacity: 1 },
          "62%": { opacity: 0.2 },
          "68%": { opacity: 0 },
          "70%": { opacity: 0 },
          "73%": { opacity: 0.5 },
          "77%": { opacity: 0 },
          "100%": { opacity: 0 },
        },
        glitch4: {
          "0%": { opacity: 0 },
          "50%": { opacity: 0 },
          "51%": { opacity: 0 },
          "79%": { opacity: 0 },
          "80%": { opacity: 0.4 },
          "83%": { opacity: 0.8 },
          "85%": { opacity: 0 },
          "100%": { opacity: 0 },
        },
        glitch5: {
          "0%": { opacity: 0 },
          "50%": { opacity: 0 },
          "51%": { opacity: 0 },
          "70%": { opacity: 0 },
          "71%": { opacity: 0.5 },
          "73%": { opacity: 0.2 },
          "74%": { opacity: 0 },
          "76%": { opacity: 0.8 },
          "77%": { opacity: 0 },
          "100%": { opacity: 0 },
        },
        glitch6: {
          "0%": { opacity: 0 },
          "50%": { opacity: 0 },
          "51%": { opacity: 0 },
          "80%": { opacity: 0 },
          "81%": { opacity: 1 },
          "83%": { opacity: 0 },
          "89%": { opacity: 0 },
          "90%": { opacity: 1 },
          "91%": { opacity: 0 },
          "100%": { opacity: 0 },
        },
      },
    },
  },
  plugins: [],
};
